### ISSUE TITLE
See components full width

### ISSUE THREAD

**Issue by pablocarrillo** [calvium/react-native-component-viewer#10]
For elements in tables would be really useful to be able to see them full width instead that a 20pt padding. Can we?
- Remove the lateral padding for all the elements
or 
- Allow a config parameter to say if we want padding for some cells or table?

Let's discuss it here and I will send a PR later

**Comment by benvium** [comment]
@pablocarrillo Agreed, this would be better. How about we remove the default horizontal padding entirely, so it can be controlled via the `wrapperStyle` param. Please keep padding for the labels though.

**Comment by pablocarrillo** [comment]
Cool, will do that.

**Comment by benvium** [comment]
when you PR could you update the package.json version as well (patch)

**Comment by pablocarrillo** [comment]
yes, already done in `remove_lateral_padding` checking before doing the PR
