### ISSUE TITLE
`addComponentTest` not playing nice with React Native hot-reloading

### ISSUE THREAD

**Issue by mattvot** [calvium/react-native-component-viewer#15]
When inside a specific component viewer I cannot seem to edit the component or change it's `addComponentTest` declaration without a hard reload.

Sometimes I can go close the viewer and re-enter to see a duplicate with new titles.

Using 0.2.2, React native 0.45.0-rc.0

**Comment by benvium** [comment]
Thanks Matt. In an ideal world a hot-reload should re-add the component tests. Sounds like this isn't happening. Will look to see if it's possible to make it work the 'right' way

**Comment by benvium** [comment]
This works as intended now.
