### ISSUE TITLE
Would be nice to lower the log level of mounted component to verbose

### ISSUE THREAD

**Issue by pablocarrillo** [calvium/react-native-component-viewer#22]
When using this the first lines in the console always looks like a big blob of text with all the names of the components which is not really useful in production

**Comment by benvium** [comment]
Agreed - feel free to PR removal of the logging of the updated text.  I've always wrapped all the tests in a `__DEV__` mode, so wouldn't expect to see anything in production mode

**Comment by pablocarrillo** [comment]
Bad choice of words, I meant when this module is used in an app development in opposition to be developed, is not actually that useful to see in the debug console the list of views loaded. So my proposal is was to use some way of verbose level login. I have just seen in https://developer.mozilla.org/en-US/docs/Web/API/Console/ that no verbose level is available so I will change the proposal to use `groupCollapsed`. 

Using `groupCollapsed` should bring a couple of good things over the other option:
- We still see an entry about the component-viewer loading
- The entry is a single line
I will put together a PR shortly

**Comment by benvium** [comment]
Sounds good. I'd make sure that console.groupCollapsed exists when running JS on the iPhone or Android (as opposed to in debug mode). I have vague memories of that not being the case in the past.
